pipeline {
    agent any

    tools {
        maven "MAVEN"
        jdk "JDK"
    }
    stages {
        stage('Initialize'){
            steps{
                git branch: 'testjunit', url: 'https://github.com/KhediraSpenser1/jenkins-pipeline-example.git'
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /opt/maven"
            }
        }
    }
}
